services:
  postgres:
    container_name: example-postgres
    image: postgres:alpine  # latest = postgres:14.15-alpine3.20
    restart: no
    volumes:
      - postgres_data:/var/lib/postgres
    ports:
      - "5432:5432"
    env_file:
      - path: .env
        required: true

volumes:
  postgres_data:
